### ISSUE TITLE
xsd:include support

### ISSUE THREAD

**Issue by iurisilvio** [FelixSchwarz/soapfish#46]
@FelixSchwarz  I was looking for `xsd:include` support in soapbox and you said soapfish implemented it. I didn't found anything about it in your code.

Can you help me with it?

**Comment by FelixSchwarz** [comment]
What do you need? Basically you use the same cli tools as with soapbox (e.g. wsdl2py) and it should just work. Can you give me a specific example (e.g. wsdl url)?

**Comment by iurisilvio** [comment]
I tried a WSDL with a `xsd:include` tag and it does not work.

I created a `xsd:include`  example based on your own example: https://github.com/iurisilvio/soapfish/commit/6798df69f82e31f157fcbc77228bfd57865434cd

For now, I'm using wsdl2java and translating all SOAP requests to my RESTful services. It is painful, I really want a Python solution. I tested this WSDL with it and worked fine.

**Comment by FelixSchwarz** [comment]
Can we close this as #55 got merged?

**Comment by iurisilvio** [comment]
Yes, closed! The `xsd:include` works. I already generated some code using private WSDLs with complicated `include`s and `import`s structure.
