### ISSUE TITLE
Relative imports

### ISSUE THREAD

**Issue by iurisilvio** [FelixSchwarz/soapfish#47]
Imports with relative schemaLocation does not work.

For example:

file1.xsd

```xml
<xsd:import schemaLocation="folder/file2.xsd" namespace="http://mynamespace.com/f1" />
```

folder/file2.xsd

```xml
<xsd:import schemaLocation="file3.xsd" namespace="http://mynamespace.com/f2" />
```

The `file3.xsd` must load `./folder/file3.xsd`, but try to load `./file3.xsd`.

I need some way to recover the parent xsd path during imports to fix this issue.

**Comment by FelixSchwarz** [comment]
good point, maybe I skipped that in my implementation (my service uses only absolute imports). Can you create a minimal example so I can check if that can be implemented in a simple way? patches welcome of course.

**Comment by iurisilvio** [comment]
I tried to patch soapbox (and soapfish is not too different), but I had some complicated edge cases.

I'll create an example with my import issues. Of course, I'll patch soapfish to solve my problem.
