### ISSUE TITLE
xsd.Decimal type does not accept a Decimal value

### ISSUE THREAD

**Issue by iurisilvio** [FelixSchwarz/soapfish#52]
A `Decimal` value is better than a `float`. It works with a string too, but I had to read the code to discover it.

https://github.com/FelixSchwarz/soapfish/blob/master/soapfish/xsd.py#L311

**Comment by FelixSchwarz** [comment]
fixed in 76c0acf52bc5d39c3010a4b3c2c77013f899d2e7
