### ISSUE TITLE
XSD elements order must not be important

### ISSUE THREAD

**Issue by iurisilvio** [FelixSchwarz/soapfish#78]
Related to #72 PR failing test.

Soapfish generate invalid code if xsd:restriction and xsd:extension are defined before the base element.

I'm trying to fix it, but I don't know the best approach:

1. Reorder XSD elements in runtime.
1. Make `EXTENSION` and `RESTRICTION` classes inherit from `ComplexType` and define the class as a class attribute.
1. Make `EXTENSION` and `RESTRICTION` render after all other types.

All of these options are not easy to implement.

Do you have any other ideas?

I can work on it, but didn't decided how to handle the problem.

**Comment by FelixSchwarz** [comment]
I think like option 1 as it seems this will require the last amount of changes for existing users and reordering could be useful for similar cases in the future. Option 2 doesn't sound too bad either, option 3 seems to be a very narrow solution (but might be worth it if the result code is ok to read).

Disclaimer: Please take these thoughts with a grain of salt. In the end we mostly need tests and maintainable code. I didn't dig too deep into the current code. If you feel that implementing nr 1 or so results in messy code, feel free to go after one of the other options. Also feel free to share "work in progress" code (e.g. by mail or in this ticket). I can't promise any timely feedback but at least I'll try.

**Comment by iurisilvio** [comment]
I didn't started it yet, but I think the option 1 is the best. Will try it this week and send some work in progress.

**Comment by iurisilvio** [comment]
It is done in my branch: https://github.com/FelixSchwarz/soapfish/compare/master...iurisilvio:xsd_reordering

I don't like the solution yet. It works for my test, but I know some failing corner cases.

**Comment by iurisilvio** [comment]
I rewrote my implementation, using the default Python `.sort(cmp)`. It looks better now.

I don't know every XSD schema detail, maybe it fails in specific cases (can I have a `xsd:extension` and `xsd:restriction` in the same `complexType`?), but I think it is good enough.

I'm trying it with my really complicated WSDLs to check if it fix my problem.

**Comment by iurisilvio** [comment]
Python 3 doesn't have the `sort(cmp=)` kwarg, but `functools.cmp_to_key` handle the problem nicely.

**Comment by iurisilvio** [comment]
I did the PR. It fixed my test and works with my WSDLs.
